{application,deepltgbot,
             [{applications,[kernel,stdlib,elixir,logger,ex_gram,tesla,
                             hackney,jason]},
              {description,"deepltgbot"},
              {modules,['Elixir.Deepltgbot','Elixir.Deepltgbot.Application',
                        'Elixir.Deepltgbot.Bot']},
              {registered,[]},
              {vsn,"0.1.0"},
              {mod,{'Elixir.Deepltgbot.Application',[]}}]}.
